version: '3.8'
services:
    ui:
        build: 
            context: ./react
        volumes:
        - ./react/src:/app/src
        - ./react/public:/app/public
        ports:
        - '80:80'
    api:
        build:
            context: ./PHP
        depends_on:
            - db
        volumes:
            - ./PHP/src:/var/www/html/
        ports:
            - 8000:80
        env_file:
          - .env
    db:
        image: mysql
        build:
          context: ./mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
volumes:
    dbdata:
